### ISSUE TITLE
Request for an Example

### ISSUE THREAD

**Issue by smitthakkar1** [drt-pkgz/lefthook#1]
Hey there,
thanks for your contribution. can you please add an example in the repo? I am not sure where to add `pre-commit` commands ? Will it be in `pubspec.yaml` ?

Thanks for your time and efforts.

**Comment by igorkamyshev** [comment]
Hello! Thanks for question. I will add example to readme, but now you can check main repo of lefthook — https://github.com/Arkweid/lefthook. Many examples are showed here.
